### ISSUE TITLE
No user friendly error when trying to login to an offline pe

### ISSUE THREAD

**Issue by Paulomart** [atlas-engine/cli#4]
If you connect to a processengine, that is offline or unreachable, the cli will throw an ugly js error:

Console output:

```bash
atlas login http://example.com
{ FetchError: invalid json response body at http://example.com/process_engine/security/authority reason: Unexpected token < in JSON at position 0
    at /Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/node-fetch/lib/index.js:272:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at http://example.com/process_engine/security/authority reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }

If your web browser does not open automatically, open this link manually to login: http://localhost:9000/login
TypeError: Cannot read property 'replace' of null
    at app.get (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/dist/commands/login/express_server.js:20:46)
    at Layer.handle [as handle_request] (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/layer.js:95:5)
    at /Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/layer.js:95:5)
```

Website output:
```plain
TypeError: Cannot read property 'replace' of null
    at app.get (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/dist/commands/login/express_server.js:20:46)
    at Layer.handle [as handle_request] (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/layer.js:95:5)
    at /Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/paulheidenreich/.nvm/versions/node/v10.17.0/lib/node_modules/@atlas-engine/cli/node_modules/express/lib/router/layer.js:95:5)
```

The cli should check if the processengine is online, before attempting to login.

**Comment by rrrene** [comment]
Das ist inzwischen gelöst.  Danke für's Reporten 👍
